create table if not exists public.marcas (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.equipos
  add column if not exists marca_id bigint references public.marcas(id) on delete set null;

alter table public.equipos
  add column if not exists estado_mantenimiento text not null default 'pendiente';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'equipos_estado_mantenimiento_valid'
  ) then
    alter table public.equipos
      add constraint equipos_estado_mantenimiento_valid
      check (estado_mantenimiento in ('pendiente', 'limpio', 'en_proceso'));
  end if;
end;
$$;

create table if not exists public.equipo_fotos (
  id bigint generated by default as identity primary key,
  equipo_id bigint not null references public.equipos(id) on delete cascade,
  url text not null,
  alt_text text,
  orden integer not null default 1,
  es_principal boolean not null default false,
  created_at timestamptz not null default now(),
  constraint equipo_fotos_orden_positive check (orden > 0)
);

create table if not exists public.equipo_historial (
  id bigint generated by default as identity primary key,
  equipo_id bigint not null,
  accion text not null,
  cambios jsonb not null default '{}'::jsonb,
  actor_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint equipo_historial_accion_valid
    check (accion in ('CREATED', 'UPDATED', 'STATUS_CHANGED', 'DELETED'))
);

create index if not exists marcas_nombre_idx on public.marcas (nombre);
create index if not exists equipos_marca_id_idx on public.equipos (marca_id);
create index if not exists equipos_estado_mantenimiento_idx
  on public.equipos (estado_mantenimiento);
create index if not exists equipo_fotos_equipo_id_idx on public.equipo_fotos (equipo_id);
create index if not exists equipo_fotos_orden_idx on public.equipo_fotos (equipo_id, orden);
create unique index if not exists equipo_fotos_principal_unique_idx
  on public.equipo_fotos (equipo_id)
  where es_principal;
create index if not exists equipo_historial_equipo_id_idx on public.equipo_historial (equipo_id);
create index if not exists equipo_historial_created_at_idx
  on public.equipo_historial (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists marcas_set_updated_at on public.marcas;
create trigger marcas_set_updated_at
before update on public.marcas
for each row
execute procedure public.set_updated_at();

insert into public.marcas (nombre)
select distinct trim(e.marca)
from public.equipos e
where e.marca is not null
  and trim(e.marca) <> ''
on conflict (nombre) do nothing;

update public.equipos e
set marca_id = m.id
from public.marcas m
where e.marca_id is null
  and e.marca is not null
  and trim(e.marca) = m.nombre;

insert into public.equipo_fotos (equipo_id, url, alt_text, orden, es_principal)
select e.id, e.foto_principal_url, null, 1, true
from public.equipos e
where e.foto_principal_url is not null
  and trim(e.foto_principal_url) <> ''
  and not exists (
    select 1
    from public.equipo_fotos f
    where f.equipo_id = e.id
  );

create or replace function public.log_equipo_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.equipo_historial (equipo_id, accion, cambios, actor_id)
    values (
      new.id,
      'CREATED',
      jsonb_build_object('after', to_jsonb(new)),
      auth.uid()
    );

    return new;
  end if;

  if tg_op = 'UPDATE' then
    insert into public.equipo_historial (equipo_id, accion, cambios, actor_id)
    values (
      new.id,
      case
        when new.activo is distinct from old.activo then 'STATUS_CHANGED'
        else 'UPDATED'
      end,
      jsonb_build_object('before', to_jsonb(old), 'after', to_jsonb(new)),
      auth.uid()
    );

    return new;
  end if;

  if tg_op = 'DELETE' then
    insert into public.equipo_historial (equipo_id, accion, cambios, actor_id)
    values (
      old.id,
      'DELETED',
      jsonb_build_object('before', to_jsonb(old)),
      auth.uid()
    );

    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists equipos_log_historial on public.equipos;
create trigger equipos_log_historial
after insert or update or delete on public.equipos
for each row
execute procedure public.log_equipo_changes();

alter table public.marcas enable row level security;
alter table public.equipo_fotos enable row level security;
alter table public.equipo_historial enable row level security;

drop policy if exists "Public read marcas" on public.marcas;
create policy "Public read marcas"
on public.marcas
for select
using (true);

drop policy if exists "Authenticated write marcas" on public.marcas;
create policy "Authenticated write marcas"
on public.marcas
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public read equipo fotos" on public.equipo_fotos;
create policy "Public read equipo fotos"
on public.equipo_fotos
for select
using (true);

drop policy if exists "Authenticated write equipo fotos" on public.equipo_fotos;
create policy "Authenticated write equipo fotos"
on public.equipo_fotos
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated read historial equipos" on public.equipo_historial;
create policy "Authenticated read historial equipos"
on public.equipo_historial
for select
to authenticated
using (true);

drop policy if exists "Authenticated write historial equipos" on public.equipo_historial;
create policy "Authenticated write historial equipos"
on public.equipo_historial
for insert
to authenticated
with check (true);
