create extension if not exists pgcrypto;

create table if not exists public.marcas (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.equipos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  marca text,
  marca_id bigint references public.marcas(id) on delete set null,
  estado_mantenimiento text not null default 'pendiente',
  descripcion text,
  advertencias_tecnicas text,
  foto_principal_url text,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint equipos_estado_mantenimiento_valid
    check (estado_mantenimiento in ('pendiente', 'limpio', 'en_proceso'))
);

create table if not exists public.equipo_fotos (
  id bigint generated by default as identity primary key,
  equipo_id bigint not null references public.equipos(id) on delete cascade,
  url text not null,
  alt_text text,
  orden integer not null default 1,
  es_principal boolean not null default false,
  created_at timestamptz not null default now(),
  constraint equipo_fotos_orden_positive check (orden > 0)
);

create table if not exists public.pasos_limpieza (
  id bigint generated by default as identity primary key,
  equipo_id bigint not null references public.equipos(id) on delete cascade,
  orden integer not null,
  titulo text not null,
  descripcion text not null,
  advertencias text,
  created_at timestamptz not null default now(),
  constraint pasos_limpieza_orden_positive check (orden > 0)
);

create table if not exists public.imagenes_paso (
  id bigint generated by default as identity primary key,
  paso_id bigint not null references public.pasos_limpieza(id) on delete cascade,
  url text not null,
  alt_text text,
  created_at timestamptz not null default now()
);

create table if not exists public.videos_equipo (
  id bigint generated by default as identity primary key,
  equipo_id bigint not null unique references public.equipos(id) on delete cascade,
  titulo text,
  url_storage text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.equipo_historial (
  id bigint generated by default as identity primary key,
  equipo_id bigint not null,
  accion text not null,
  cambios jsonb not null default '{}'::jsonb,
  actor_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint equipo_historial_accion_valid
    check (accion in ('CREATED', 'UPDATED', 'STATUS_CHANGED', 'DELETED'))
);

create index if not exists marcas_nombre_idx on public.marcas (nombre);
create index if not exists equipos_activo_idx on public.equipos (activo);
create index if not exists equipos_nombre_idx on public.equipos (nombre);
create index if not exists equipos_marca_idx on public.equipos (marca);
create index if not exists equipos_marca_id_idx on public.equipos (marca_id);
create index if not exists equipos_estado_mantenimiento_idx
  on public.equipos (estado_mantenimiento);
create index if not exists equipo_fotos_equipo_id_idx on public.equipo_fotos (equipo_id);
create index if not exists equipo_fotos_orden_idx on public.equipo_fotos (equipo_id, orden);
create unique index if not exists equipo_fotos_principal_unique_idx
  on public.equipo_fotos (equipo_id)
  where es_principal;
create index if not exists pasos_limpieza_equipo_id_idx on public.pasos_limpieza (equipo_id);
create index if not exists imagenes_paso_paso_id_idx on public.imagenes_paso (paso_id);
create index if not exists equipo_historial_equipo_id_idx on public.equipo_historial (equipo_id);
create index if not exists equipo_historial_created_at_idx
  on public.equipo_historial (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists marcas_set_updated_at on public.marcas;
create trigger marcas_set_updated_at
before update on public.marcas
for each row
execute procedure public.set_updated_at();

drop trigger if exists equipos_set_updated_at on public.equipos;
create trigger equipos_set_updated_at
before update on public.equipos
for each row
execute procedure public.set_updated_at();

create or replace function public.log_equipo_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.equipo_historial (equipo_id, accion, cambios, actor_id)
    values (
      new.id,
      'CREATED',
      jsonb_build_object('after', to_jsonb(new)),
      auth.uid()
    );

    return new;
  end if;

  if tg_op = 'UPDATE' then
    insert into public.equipo_historial (equipo_id, accion, cambios, actor_id)
    values (
      new.id,
      case
        when new.activo is distinct from old.activo then 'STATUS_CHANGED'
        else 'UPDATED'
      end,
      jsonb_build_object('before', to_jsonb(old), 'after', to_jsonb(new)),
      auth.uid()
    );

    return new;
  end if;

  if tg_op = 'DELETE' then
    insert into public.equipo_historial (equipo_id, accion, cambios, actor_id)
    values (
      old.id,
      'DELETED',
      jsonb_build_object('before', to_jsonb(old)),
      auth.uid()
    );

    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists equipos_log_historial on public.equipos;
create trigger equipos_log_historial
after insert or update or delete on public.equipos
for each row
execute procedure public.log_equipo_changes();

alter table public.marcas enable row level security;
alter table public.equipos enable row level security;
alter table public.equipo_fotos enable row level security;
alter table public.pasos_limpieza enable row level security;
alter table public.imagenes_paso enable row level security;
alter table public.videos_equipo enable row level security;
alter table public.equipo_historial enable row level security;

drop policy if exists "Public read marcas" on public.marcas;
create policy "Public read marcas"
on public.marcas
for select
using (true);

drop policy if exists "Authenticated write marcas" on public.marcas;
create policy "Authenticated write marcas"
on public.marcas
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public read equipos" on public.equipos;
create policy "Public read equipos"
on public.equipos
for select
using (true);

drop policy if exists "Authenticated write equipos" on public.equipos;
create policy "Authenticated write equipos"
on public.equipos
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public read equipo fotos" on public.equipo_fotos;
create policy "Public read equipo fotos"
on public.equipo_fotos
for select
using (true);

drop policy if exists "Authenticated write equipo fotos" on public.equipo_fotos;
create policy "Authenticated write equipo fotos"
on public.equipo_fotos
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public read pasos" on public.pasos_limpieza;
create policy "Public read pasos"
on public.pasos_limpieza
for select
using (true);

drop policy if exists "Authenticated write pasos" on public.pasos_limpieza;
create policy "Authenticated write pasos"
on public.pasos_limpieza
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public read imagenes" on public.imagenes_paso;
create policy "Public read imagenes"
on public.imagenes_paso
for select
using (true);

drop policy if exists "Authenticated write imagenes" on public.imagenes_paso;
create policy "Authenticated write imagenes"
on public.imagenes_paso
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public read videos" on public.videos_equipo;
create policy "Public read videos"
on public.videos_equipo
for select
using (true);

drop policy if exists "Authenticated write videos" on public.videos_equipo;
create policy "Authenticated write videos"
on public.videos_equipo
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated read historial equipos" on public.equipo_historial;
create policy "Authenticated read historial equipos"
on public.equipo_historial
for select
to authenticated
using (true);

drop policy if exists "Authenticated write historial equipos" on public.equipo_historial;
create policy "Authenticated write historial equipos"
on public.equipo_historial
for insert
to authenticated
with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'protocolo-imagenes',
  'protocolo-imagenes',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'protocolo-videos',
  'protocolo-videos',
  true,
  524288000,
  array['video/mp4', 'video/webm', 'video/quicktime']
)
on conflict (id) do nothing;

drop policy if exists "Public read protocol files" on storage.objects;
create policy "Public read protocol files"
on storage.objects
for select
using (bucket_id in ('protocolo-imagenes', 'protocolo-videos'));

drop policy if exists "Authenticated upload protocol files" on storage.objects;
create policy "Authenticated upload protocol files"
on storage.objects
for insert
to authenticated
with check (bucket_id in ('protocolo-imagenes', 'protocolo-videos'));

drop policy if exists "Authenticated update protocol files" on storage.objects;
create policy "Authenticated update protocol files"
on storage.objects
for update
to authenticated
using (bucket_id in ('protocolo-imagenes', 'protocolo-videos'))
with check (bucket_id in ('protocolo-imagenes', 'protocolo-videos'));

drop policy if exists "Authenticated delete protocol files" on storage.objects;
create policy "Authenticated delete protocol files"
on storage.objects
for delete
to authenticated
using (bucket_id in ('protocolo-imagenes', 'protocolo-videos'));
